<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>$(_AndroidTargetFrameworks)</TargetFrameworks>
    <SupportedOSPlatformVersion>$(_SupportedOSPlatformAndroidVersion)</SupportedOSPlatformVersion>
    
    <AssemblyName>Com.Zerobranch.SwipeLayout</AssemblyName>
    <RootNamespace>Com.Zerobranch.SwipeLayout</RootNamespace>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <RunAOTAnalysis>true</RunAOTAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  
  <PropertyGroup>
    <Description>Binding library of https://github.com/zerobranch/SwipeLayout</Description>
    <PackageId>Nivaes.Droid.Zerobranch.SwipeLayout</PackageId>
    <PackageTags>xamarin;android;nivaes;zerobranch;swipelayout</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup>
    <IsBindingProject>true</IsBindingProject>
    <OutputType>Library</OutputType>
    <AndroidClassParser>class-parse</AndroidClassParser>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" />
  </ItemGroup>

</Project>
