<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(_SampleAndroidTargetFramework)</TargetFramework>
    <SupportedOSPlatformVersion>$(_SupportedOSPlatformAndroidVersion)</SupportedOSPlatformVersion>

    <AssemblyName>Nivaes.Zerobranch.SwipeLayout.Droid</AssemblyName>
    <RootNamespace>Nivaes.Zerobranch.SwipeLayout.Droid</RootNamespace>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" />
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nivaes.Droid.Zerobranch.SwipeLayout\Nivaes.Droid.Zerobranch.SwipeLayout.csproj" />
  </ItemGroup>
  
</Project>
